#!/usr/bin/env bash

script_dir="$(dirname "$0")"

if [[ ! $1 ]]; then
    python3 -m akr_extensions -h
else
    case "$1" in
        "add")
            if [[ ! $2 ]]; then
                echo "You need to pass a pypi package extension"
            else
                pip install "$2"
                python3 -m akr_extensions "$1" "$2"
            fi
            ;;
        "list")
            python3 -m akr_extensions "$1"
            ;;
        "remove")
            if [[ ! $2 ]]; then
                echo "You need to pass a the name of an"
            else
                pip uninstall $2 <<< "y"
                python3 -m akr_extensions "$1" "$2"
            fi
            ;;
        "set-default")
            if [[ ! $2 ]]; then
                echo "You need to pass a the name of an extension"
            else
                if pip show "$2" &> /dev/null; then
                    python3 -m akr_extensions "$1" "$2"
                else
                    echo "Extension is not installed"
                fi
            fi
            ;;
        *)
            python3 -m akr_extensions -h
            ;;

    esac

fi